version: '3.8'

services:
  web:
    build: ./backend
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    networks:
      - kong-net

  db:
    image: mysql:8.0
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql      
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    networks:
      - kong-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8089:80"
    depends_on:
      - db

volumes:
  db-data:


networks:
  kong-net:
    name: kong-net
    driver: bridge