version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0

  db:
    image: mysql:5.7
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql      
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data:
